### ISSUE TITLE
focus states don't appear for hover menus and some buttons

### ISSUE THREAD

**Issue by katestud** [vigetlabs/active_material#17]
Hello! I did some quick keyboard navigation testing on the switch CMS. A couple items can be selected by the keyboard, but don't show any sort of visible focus state.

Screenshots and video:
* https://s3.amazonaws.com/vigesharing-is-vigecaring/kstudwell/Pages__Switch_CMS_2015-12-10_10-05-03.png
* https://s3.amazonaws.com/vigesharing-is-vigecaring/kstudwell/screencast_2015-12-10_10-08-34.mp4

Login to Switch CMS: https://vigesafe.lab.viget.com/passwords/6f184710-e3db-45c5-8634-ec4d3304856c

Visit any of the content listing pages, try "Pages" from the top admin.

Use the "Tab" key to navigate the page. Items that don't appear with a focus state:
* User icon in top right - this should open a dropdown on hover with a couple options
* "New Page" button in top right - this is just a single button
* "Settings" button to the right of each instance of a page. This should open a dropdown on hover with a few options

While tabbing through the page, you can see that the URLs are accessible, but from a user perspective, it's not clear where you'll end up if you hit enter.

Let me know if you have any questions!

**Comment by nhunzaker** [comment]
We finally landed this!
