### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by defec8edc0de** [vigetlabs/active_material#23]
Thanks for the great work, but I had some problem during installation...

Why is the recommended gem installation this way:
`gem "active_material", git: "git@github.com:vigetlabs/active_material.git"`
and not this way?
`gem "active_material", git: "https://github.com/vigetlabs/active_material.git"`

I got a **Permission Denied (publickey)** error while try to run bundle...
This link helped me to solve the issue:
[Fail: Permission denied from GitHub on bundle install](https://semaphoreci.com/docs/fail-permission-denied-from-github.html)

**Comment by nhunzaker** [comment]
No good reason. We should actually probably do:

```
gem "active_material", github: "vigetlabs/active_material"
```

What do you prefer?

**Comment by defec8edc0de** [comment]
I would prefer indeed your recommendation :-)
