### ISSUE TITLE
Utility Nav breaks if it haves multiple items

### ISSUE THREAD

**Issue by jdsampayo** [vigetlabs/active_material#32]
Before active_admin:
<img width="273" alt="screen shot 2016-12-21 at 2 50 35 pm" src="https://cloud.githubusercontent.com/assets/1060579/21405652/dc7943a2-c78c-11e6-959a-87622874b7f6.png">

After:
<img width="246" alt="screen shot 2016-12-21 at 2 49 22 pm" src="https://cloud.githubusercontent.com/assets/1060579/21405640/cc53268c-c78c-11e6-8d25-0b283c2d4da3.png">

**Comment by joshlin** [comment]
You can fix it by adding css (similar to id=current_user) to the new menu item. However, the problem is that the menu item's position is fixed. If you have dynamic menu items, I can not figure it out. I hope someone know the workaround.
