### ISSUE TITLE
Can't get it to work - Sass parsing error 

### ISSUE THREAD

**Issue by ninjarabbi** [vigetlabs/active_material#35]
I'm getting this error when trying to open my admin page:

`Sass::SyntaxError - Invalid CSS after "...               ": expected ")", was ": $am-theme-acc..."`

and it points to my active_admin.css.scss file.

Just in case, I commented out everything I had in there except `@import "active_material";` and it still happens.

**Comment by nhunzaker** [comment]
What version of Sass?

**Comment by nhunzaker** [comment]
Reason I ask, we use a map to store the color variables:

https://github.com/vigetlabs/active_material/blob/master/app/assets/stylesheets/active_material/values/colors.scss#L84-L85

It's possible your version of Sass does not support this feature.

**Comment by ninjarabbi** [comment]
I has sass-rails at 4.0.2 and I upgraded it to 5.0.6 and that fixed it, thanks
