### ISSUE TITLE
Initial setup issue

### ISSUE THREAD

**Issue by AdamFreemer** [vigetlabs/active_material#61]
I have active admin up and working just fine, but can't seem to debug this after following the installation instructions exactly as detailed, any advice? (on /admin load)

`ActionView::Template::Error (File to import not found or unreadable: active_material/values/*`

**Comment by RDeckard** [comment]
Workarround:
https://github.com/platanus/activeadmin_addons/issues/156#issuecomment-339623146

**Comment by nhunzaker** [comment]
Ouch... Sorry!

@RDeckard should we make this a part of our setup instructions?

**Comment by RDeckard** [comment]
Maybe it will work by « Register `gem 'sass-rails'` as an explicit dependency » of ActiveMaterial ?
If so, it will be easier for your users :). Sorry I’m on mobile I can’t open a PR.

**Comment by nhunzaker** [comment]
Just merged a PR that does that, :+1:
