### ISSUE TITLE
Style modal window

### ISSUE THREAD

**Issue by zporter** [vigetlabs/active_material#8]
When using ActiveAdmin's batch actions feature, a modal is used to confirm performing an action (see screenshot below):

![](https://dl.dropboxusercontent.com/u/6992819/screenshots/Screen%20Shot%202015-08-10%20at%2010.19.20%20AM.png)

It looks pretty decent already, but probably could use a little love, especially around highlighting the OK button over the Cancel button.

Thanks!

**Comment by nhunzaker** [comment]
This is now checked in as of 1.4.
